/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    authors: Author;
    posts: Post;
    tags: Tag;
    categories: Category;
    Menu: Menu;
    technologies: Technology;
    projects: Project;
    testimonials: Testimonial;
    company: Company;
    services: Service;
    industries: Industry;
    'free-consultations': FreeConsultation;
    'consultation-page': ConsultationPage;
    faqs: Faq;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    Menu: MenuSelect<false> | MenuSelect<true>;
    technologies: TechnologiesSelect<false> | TechnologiesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    company: CompanySelect<false> | CompanySelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    'free-consultations': FreeConsultationsSelect<false> | FreeConsultationsSelect<true>;
    'consultation-page': ConsultationPageSelect<false> | ConsultationPageSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'email-templates': EmailTemplate;
    footer: Footer;
    'global-schema': GlobalSchema;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'email-templates': EmailTemplatesSelect<false> | EmailTemplatesSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'global-schema': GlobalSchemaSelect<false> | GlobalSchemaSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  parent?: (string | null) | Page;
  order?: number | null;
  servicesPageContent?: {
    heroTitle?: string | null;
    heroSubtitle?: string | null;
    heroButtons?:
      | {
          text?: string | null;
          link?: string | null;
          id?: string | null;
        }[]
      | null;
    sections?:
      | {
          category: 'ai' | 'web' | 'cloud' | 'marketing';
          label?: string | null;
          heading?: string | null;
          subheading?: string | null;
          description?: string | null;
          cardNote?: string | null;
          exploreLabel?: string | null;
          exploreLink?: string | null;
          bullets?:
            | {
                text?: string | null;
                id?: string | null;
              }[]
            | null;
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  contactPageContent?: {
    heroTitle?: string | null;
    heroHighlight?: string | null;
    heroSubtitle?: string | null;
    contactHeading?: string | null;
    contactDescription?: string | null;
    ctaTitle?: string | null;
    ctaDescription?: string | null;
    ctaButtonLabel?: string | null;
    ctaButtonLink?: string | null;
  };
  hireDevelopersPageContent?: {
    heroTitleLine1?: string | null;
    heroTitleLine2?: string | null;
    heroSubtitle?: string | null;
    heroCtaLabel?: string | null;
    heroCtaLink?: string | null;
    heroImage?: (string | null) | Media;
    heroImageAlt?: string | null;
    skillsEyebrow?: string | null;
    skillsHeading?: string | null;
    skills?:
      | {
          label: string;
          icon?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Used for SEO purposes. Appears in the <title> tag.
   */
  metaTitle?: string | null;
  /**
   * Used for SEO purposes. Appears in the <meta name="description" /> tag.
   */
  metaDescription?: string | null;
  openGraph?: {
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (string | null) | Media;
  };
  blocks?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            backgroundImage?: (string | null) | Media;
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            buttons?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            'Side-1'?: {
              'Left Heading'?: string | null;
              Description?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              Image?: (string | null) | Media;
              blobcard?:
                | {
                    label?: string | null;
                    value?: string | null;
                    id?: string | null;
                  }[]
                | null;
              Button?:
                | {
                    'Button Text'?: string | null;
                    'Button Link'?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            'Side-2'?: {
              'Right Heading'?: string | null;
              image?: (string | null) | Media;
              Description?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              blobcard?:
                | {
                    label?: string | null;
                    value?: string | null;
                    id?: string | null;
                  }[]
                | null;
              Cards?:
                | {
                    heading?: string | null;
                    description?: string | null;
                    image?: (string | null) | Media;
                    button?:
                      | {
                          'Button Text'?: string | null;
                          'Button Link'?: string | null;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                  }[]
                | null;
              Button?:
                | {
                    'Button Text'?: string | null;
                    'Button Link'?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'Side-by-Side-Section';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            image?: (string | null) | Media;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            blobcard?:
              | {
                  label?: string | null;
                  value?: string | null;
                  id?: string | null;
                }[]
              | null;
            Cards?:
              | {
                  heading?: string | null;
                  description?: string | null;
                  image?: (string | null) | Media;
                  button?:
                    | {
                        'Button Text'?: string | null;
                        'Button Link'?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  'tech-data'?: (string | Technology)[] | null;
                  id?: string | null;
                }[]
              | null;
            Button?:
              | {
                  'Button Text'?: string | null;
                  'Button Link'?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'Single-Column-Section';
          }
        | {
            heading?: string | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            subheading?: string | null;
            ratingLabel?: string | null;
            ratingValue?: string | null;
            ratingStars?: number | null;
            testimonialtype?: ('slider' | 'grid') | null;
            'testimonial data'?: (string | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'Testimonials';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            button?:
              | {
                  'Button Text'?: string | null;
                  'Button Link'?: string | null;
                  id?: string | null;
                }[]
              | null;
            'projects data'?: (string | Project)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'Projects';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            'form fields'?: (string | null) | Form;
            id?: string | null;
            blockName?: string | null;
            blockType: 'Forms';
          }
        | {
            image?: (string | null) | Media;
            heading?: string | null;
            subheading?: string | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageAndText';
          }
        | {
            heading?: string | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            subheading?: string | null;
            'Tech Type'?: ('slider' | 'grid') | null;
            'techdata data'?: (string | Technology)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'Technologies';
          }
        | {
            tags?: (string | Tag)[] | null;
            faqs?: (string | Faq)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqs';
          }
        | {
            heading?: string | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            cards?:
              | {
                  heading: string;
                  description: string;
                  image?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'Why-Us';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (string | null) | Media;
    /**
     * Paste JSON-LD structured data here.
     */
    schema?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies".
 */
export interface Technology {
  id: string;
  name?: string | null;
  logo?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  name: string;
  heading?: string | null;
  testimonial: string;
  testimonialname?: string | null;
  testimonialposition?: string | null;
  rating?: number | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title?: string | null;
  description?: string | null;
  slug?: string | null;
  technologies?:
    | {
        technology?: (string | Technology)[] | null;
        id?: string | null;
      }[]
    | null;
  Section?:
    | {
        title?: string | null;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        additional?:
          | {
              additional?: string | null;
              id?: string | null;
            }[]
          | null;
        images?:
          | {
              image?: (string | null) | Media;
              id?: string | null;
            }[]
          | null;
        projects?: (string | Testimonial)[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  description?: string | null;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Primary recipient for submissions from this form.
   */
  receiverEmail?: string | null;
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  question: string;
  answer: string;
  tags?: (string | Tag)[] | null;
  isActive?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: string;
  name: string;
  slug?: string | null;
  bio?: string | null;
  avatar?: (string | null) | Media;
  socialLinks?: {
    twitter?: string | null;
    linkedin?: string | null;
    github?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (string | null) | Media;
  author?: (string | null) | User;
  publishedAt?: string | null;
  tags?: (string | Tag)[] | null;
  readtime?: number | null;
  categories?: (string | Category)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  slug?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Menu".
 */
export interface Menu {
  id: string;
  title: string;
  Items?:
    | {
        label: string;
        slug?: string | null;
        description?: string | null;
        href?: string | null;
        hasDropdown?: boolean | null;
        sourceCollection?: ('none' | 'company' | 'services' | 'industries') | null;
        dropdownItems?:
          | {
              categoryTitle: string;
              slug?: string | null;
              image?: (string | null) | Media;
              link?: string | null;
              subServices?:
                | {
                    label: string;
                    description?: string | null;
                    link?: string | null;
                    slug?: string | null;
                    id?: string | null;
                  }[]
                | null;
              logoorimage?: (string | null) | Media;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company".
 */
export interface Company {
  id: string;
  title: string;
  /**
   * URL slug (e.g. about-us, core-team)
   */
  slug: string;
  shortDescription?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Menu order
   */
  order?: number | null;
  showInMenu?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  /**
   * URL slug (e.g. ai-consulting, web-development)
   */
  slug: string;
  category?: ('ai' | 'web' | 'cloud' | 'marketing') | null;
  shortDescription?: string | null;
  icon?: (string | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  showInMenu?: boolean | null;
  order?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (string | null) | Media;
    /**
     * Paste JSON-LD structured data here.
     */
    schema?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: string;
  title: string;
  slug: string;
  shortDescription?: string | null;
  /**
   * Overrides the main hero heading for this industry page.
   */
  heroTitle?: string | null;
  /**
   * Hero subheading/summary shown under the main title.
   */
  heroDescription?: string | null;
  /**
   * Hero CTA button text.
   */
  heroCtaText?: string | null;
  /**
   * Hero CTA button link (e.g. /contact-us).
   */
  heroCtaLink?: string | null;
  /**
   * Hero image shown on the right side of the industry hero.
   */
  heroImage?: (string | null) | Media;
  icon?: (string | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Framework section for single industry page
   */
  frameworkSection?: {
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    features?:
      | {
          icon?: ('robot' | 'shield' | 'sync') | null;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Strategy section for single industry page
   */
  strategySection: {
    eyebrow?: string | null;
    heading: string;
    description: string;
    ctaText?: string | null;
    services?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Achievement section for single industry page
   */
  achievementSection?: {
    heading?: string | null;
    description?: string | null;
    cards?:
      | {
          title: string;
          subtitle?: string | null;
          description?: string | null;
          light?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Why Us section for single industry page
   */
  whyUsSection?: {
    heading?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    cards?:
      | {
          heading: string;
          description: string;
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Trusted By section for single industry page
   */
  trustedBySection?: {
    heading?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    logos?:
      | {
          name?: string | null;
          logo?: (string | null) | Media;
          /**
           * Optional external logo URL if no media upload is provided.
           */
          logoUrl?: string | null;
          id?: string | null;
        }[]
      | null;
    blobcard?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  showInMenu?: boolean | null;
  order?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (string | null) | Media;
    /**
     * Paste JSON-LD structured data here.
     */
    schema?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "free-consultations".
 */
export interface FreeConsultation {
  id: string;
  fullName?: string | null;
  email?: string | null;
  phone?: string | null;
  idea?: string | null;
  slot?: string | null;
  preferredDate?: string | null;
  rawData:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-page".
 */
export interface ConsultationPage {
  id: string;
  heading: string;
  subheading: string;
  consultationModal?: {
    modalEyebrow?: string | null;
    modalHeading?: string | null;
    modalDescription?: string | null;
    modalBenefits?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    modalTrustLine?: string | null;
    formEyebrow?: string | null;
    formHeading?: string | null;
    formDescription?: string | null;
    ctaLabel?: string | null;
    securityLine?: string | null;
  };
  evaluationOptions?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  serviceOptions?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'authors';
        value: string | Author;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'Menu';
        value: string | Menu;
      } | null)
    | ({
        relationTo: 'technologies';
        value: string | Technology;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'company';
        value: string | Company;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'industries';
        value: string | Industry;
      } | null)
    | ({
        relationTo: 'free-consultations';
        value: string | FreeConsultation;
      } | null)
    | ({
        relationTo: 'consultation-page';
        value: string | ConsultationPage;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  order?: T;
  servicesPageContent?:
    | T
    | {
        heroTitle?: T;
        heroSubtitle?: T;
        heroButtons?:
          | T
          | {
              text?: T;
              link?: T;
              id?: T;
            };
        sections?:
          | T
          | {
              category?: T;
              label?: T;
              heading?: T;
              subheading?: T;
              description?: T;
              cardNote?: T;
              exploreLabel?: T;
              exploreLink?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              image?: T;
              id?: T;
            };
      };
  contactPageContent?:
    | T
    | {
        heroTitle?: T;
        heroHighlight?: T;
        heroSubtitle?: T;
        contactHeading?: T;
        contactDescription?: T;
        ctaTitle?: T;
        ctaDescription?: T;
        ctaButtonLabel?: T;
        ctaButtonLink?: T;
      };
  hireDevelopersPageContent?:
    | T
    | {
        heroTitleLine1?: T;
        heroTitleLine2?: T;
        heroSubtitle?: T;
        heroCtaLabel?: T;
        heroCtaLink?: T;
        heroImage?: T;
        heroImageAlt?: T;
        skillsEyebrow?: T;
        skillsHeading?: T;
        skills?:
          | T
          | {
              label?: T;
              icon?: T;
              id?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  openGraph?:
    | T
    | {
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              text?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'Side-by-Side-Section'?:
          | T
          | {
              'Side-1'?:
                | T
                | {
                    'Left Heading'?: T;
                    Description?: T;
                    Image?: T;
                    blobcard?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                    Button?:
                      | T
                      | {
                          'Button Text'?: T;
                          'Button Link'?: T;
                          id?: T;
                        };
                  };
              'Side-2'?:
                | T
                | {
                    'Right Heading'?: T;
                    image?: T;
                    Description?: T;
                    blobcard?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                    Cards?:
                      | T
                      | {
                          heading?: T;
                          description?: T;
                          image?: T;
                          button?:
                            | T
                            | {
                                'Button Text'?: T;
                                'Button Link'?: T;
                                id?: T;
                              };
                          id?: T;
                        };
                    Button?:
                      | T
                      | {
                          'Button Text'?: T;
                          'Button Link'?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        'Single-Column-Section'?:
          | T
          | {
              heading?: T;
              subheading?: T;
              image?: T;
              description?: T;
              blobcard?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              Cards?:
                | T
                | {
                    heading?: T;
                    description?: T;
                    image?: T;
                    button?:
                      | T
                      | {
                          'Button Text'?: T;
                          'Button Link'?: T;
                          id?: T;
                        };
                    'tech-data'?: T;
                    id?: T;
                  };
              Button?:
                | T
                | {
                    'Button Text'?: T;
                    'Button Link'?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        Testimonials?:
          | T
          | {
              heading?: T;
              description?: T;
              subheading?: T;
              ratingLabel?: T;
              ratingValue?: T;
              ratingStars?: T;
              testimonialtype?: T;
              'testimonial data'?: T;
              id?: T;
              blockName?: T;
            };
        Projects?:
          | T
          | {
              heading?: T;
              subheading?: T;
              description?: T;
              button?:
                | T
                | {
                    'Button Text'?: T;
                    'Button Link'?: T;
                    id?: T;
                  };
              'projects data'?: T;
              id?: T;
              blockName?: T;
            };
        Forms?:
          | T
          | {
              heading?: T;
              subheading?: T;
              description?: T;
              'form fields'?: T;
              id?: T;
              blockName?: T;
            };
        imageAndText?:
          | T
          | {
              image?: T;
              heading?: T;
              subheading?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        Technologies?:
          | T
          | {
              heading?: T;
              description?: T;
              subheading?: T;
              'Tech Type'?: T;
              'techdata data'?: T;
              id?: T;
              blockName?: T;
            };
        faqs?:
          | T
          | {
              tags?: T;
              faqs?: T;
              id?: T;
              blockName?: T;
            };
        'Why-Us'?:
          | T
          | {
              heading?: T;
              description?: T;
              cards?:
                | T
                | {
                    heading?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        schema?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  avatar?: T;
  socialLinks?:
    | T
    | {
        twitter?: T;
        linkedin?: T;
        github?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  publishedAt?: T;
  tags?: T;
  readtime?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  title?: T;
  Items?:
    | T
    | {
        label?: T;
        slug?: T;
        description?: T;
        href?: T;
        hasDropdown?: T;
        sourceCollection?: T;
        dropdownItems?:
          | T
          | {
              categoryTitle?: T;
              slug?: T;
              image?: T;
              link?: T;
              subServices?:
                | T
                | {
                    label?: T;
                    description?: T;
                    link?: T;
                    slug?: T;
                    id?: T;
                  };
              logoorimage?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies_select".
 */
export interface TechnologiesSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slug?: T;
  technologies?:
    | T
    | {
        technology?: T;
        id?: T;
      };
  Section?:
    | T
    | {
        title?: T;
        description?: T;
        additional?:
          | T
          | {
              additional?: T;
              id?: T;
            };
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        projects?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  heading?: T;
  testimonial?: T;
  testimonialname?: T;
  testimonialposition?: T;
  rating?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company_select".
 */
export interface CompanySelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  content?: T;
  order?: T;
  showInMenu?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  shortDescription?: T;
  icon?: T;
  content?: T;
  showInMenu?: T;
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        schema?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  heroTitle?: T;
  heroDescription?: T;
  heroCtaText?: T;
  heroCtaLink?: T;
  heroImage?: T;
  icon?: T;
  content?: T;
  frameworkSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        features?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  strategySection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        ctaText?: T;
        services?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  achievementSection?:
    | T
    | {
        heading?: T;
        description?: T;
        cards?:
          | T
          | {
              title?: T;
              subtitle?: T;
              description?: T;
              light?: T;
              id?: T;
            };
      };
  whyUsSection?:
    | T
    | {
        heading?: T;
        description?: T;
        cards?:
          | T
          | {
              heading?: T;
              description?: T;
              image?: T;
              id?: T;
            };
      };
  trustedBySection?:
    | T
    | {
        heading?: T;
        description?: T;
        logos?:
          | T
          | {
              name?: T;
              logo?: T;
              logoUrl?: T;
              id?: T;
            };
        blobcard?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  showInMenu?: T;
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        schema?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "free-consultations_select".
 */
export interface FreeConsultationsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  idea?: T;
  slot?: T;
  preferredDate?: T;
  rawData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-page_select".
 */
export interface ConsultationPageSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  consultationModal?:
    | T
    | {
        modalEyebrow?: T;
        modalHeading?: T;
        modalDescription?: T;
        modalBenefits?:
          | T
          | {
              text?: T;
              id?: T;
            };
        modalTrustLine?: T;
        formEyebrow?: T;
        formHeading?: T;
        formDescription?: T;
        ctaLabel?: T;
        securityLine?: T;
      };
  evaluationOptions?:
    | T
    | {
        label?: T;
        id?: T;
      };
  serviceOptions?:
    | T
    | {
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  tags?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  receiverEmail?: T;
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates".
 */
export interface EmailTemplate {
  id: string;
  brandName?: string | null;
  supportEmail?: string | null;
  websiteUrl?: string | null;
  /**
   * Primary recipient for contact and consultation submissions.
   */
  adminEmail?: string | null;
  /**
   * Optional list to send to multiple recipients. Used in addition to the primary receiver email.
   */
  adminRecipients?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  adminSubject?: string | null;
  /**
   * HTML allowed. Use placeholders like {{fullName}}, {{email}}, {{phone}}, {{idea}}, {{slot}}, {{preferredDate}}, {{table}}.
   */
  adminBody?: string | null;
  userSubject?: string | null;
  /**
   * HTML allowed. Use placeholders like {{fullName}}, {{brandName}}, {{supportEmail}}, {{websiteUrl}}.
   */
  userBody?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Applies to footer sections only.
   */
  useDefaultContent?: boolean | null;
  sections?:
    | {
        sectionKey: 'about' | 'services' | 'technologies' | 'industries' | 'custom';
        title: string;
        links?:
          | {
              linkType?: ('page' | 'custom') | null;
              /**
               * Select a page to auto-fill Link Text and Link URL.
               */
              page?: (string | null) | Page;
              /**
               * Optional override. Leave empty to use the page title.
               */
              label: string;
              /**
               * Optional override. Auto-filled from the selected page slug.
               */
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  showContactForm?: boolean | null;
  contactForm?: (string | null) | Form;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-schema".
 */
export interface GlobalSchema {
  id: string;
  /**
   * Paste JSON-LD structured data here.
   */
  schema?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  favicon?: (string | null) | Media;
  /**
   * Use this if you want to paste a direct image URL instead of uploading.
   */
  faviconUrl?: string | null;
  headerLogo?: (string | null) | Media;
  footerLogo?: (string | null) | Media;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    locationLink?: string | null;
    locationText?: string | null;
  };
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'linkedin' | 'twitter';
        url: string;
        id?: string | null;
      }[]
    | null;
  tagline?: string | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
  brandName?: T;
  supportEmail?: T;
  websiteUrl?: T;
  adminEmail?: T;
  adminRecipients?:
    | T
    | {
        email?: T;
        id?: T;
      };
  adminSubject?: T;
  adminBody?: T;
  userSubject?: T;
  userBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  useDefaultContent?: T;
  sections?:
    | T
    | {
        sectionKey?: T;
        title?: T;
        links?:
          | T
          | {
              linkType?: T;
              page?: T;
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  showContactForm?: T;
  contactForm?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-schema_select".
 */
export interface GlobalSchemaSelect<T extends boolean = true> {
  schema?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  favicon?: T;
  faviconUrl?: T;
  headerLogo?: T;
  footerLogo?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
        locationLink?: T;
        locationText?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  tagline?: T;
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}